table customer
	lineageTag: 79e84e75-9d5d-4e5b-850d-bf16978066d1

	column C_CUSTKEY
		dataType: int64
		formatString: 0
		lineageTag: d49157f7-1765-412a-b512-688bd7eb6627
		summarizeBy: none
		sourceColumn: C_CUSTKEY

		annotation SummarizationSetBy = Automatic

	column C_NAME
		dataType: string
		lineageTag: 100cc830-eae3-4162-aaf2-1a3062782baf
		summarizeBy: none
		sourceColumn: C_NAME

		annotation SummarizationSetBy = Automatic

	column C_NATIONKEY
		dataType: int64
		formatString: 0
		lineageTag: f594193b-1260-4ff2-87ac-a06313edddf3
		summarizeBy: none
		sourceColumn: C_NATIONKEY

		annotation SummarizationSetBy = Automatic

	column C_ACCTBAL
		dataType: double
		lineageTag: b08b8be8-b78e-4ad8-800d-f6bdf14daded
		summarizeBy: sum
		sourceColumn: C_ACCTBAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column C_MKTSEGMENT
		dataType: string
		lineageTag: 7f0b9429-567e-44e9-84b2-d6a54a8d8c32
		summarizeBy: none
		sourceColumn: C_MKTSEGMENT

		annotation SummarizationSetBy = Automatic

	partition customer = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("adb-2219810816778143.3.azuredatabricks.net", "/sql/1.0/warehouses/6fdebb669d2772a3", [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),
				    samples_Database = Source{[Name="hive_metastore",Kind="Database"]}[Data],
				    tpch_Schema = samples_Database{[Name="tpch_sf1_delta_nopartitions",Kind="Schema"]}[Data],
				    customer_Table = tpch_Schema{[Name="customer",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(customer_Table,{"C_ADDRESS", "C_COMMENT", "C_PHONE"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

