name: Release

# Triggers when a tag v* is created on main
on:
  push:
    #branches: [ "main" ]
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: {}

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on:
      group: databricks-solutions-protected-runner-group
      labels: linux-ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        #uses: actions/checkout@v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --generate-notes --latest
          #--draft false --prerelease false --make-latest true