name: Release

# Triggers when a tag v* is created on main
on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  contents: write

jobs:
  build:
    runs-on:
      group: databricks-protected-runner-group
      labels: linux-ubuntu-latest

    steps:
      - name: Checkout
        #uses: actions/checkout@v6
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6 (pin)
                
      - name: Archive files
        #uses: thedoctor0/zip-release@0.7.5
        uses: thedoctor0/zip-release@7fddfdd07cadb5b8c6c0dbcdcec17f8cd7784b80 # 0.7.5 (pin)
        with:
          type: 'zip'
          filename: "powerbi-on-databricks-migration-accelerator-${{ github.ref_name }}.zip"
          exclusions: '*.git* .editorconfig .git/**'

      - name: Create release
        #uses: softprops/action-gh-release@v3
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda  # v3 (pin)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
          make_latest: true
          files: |
            powerbi-on-databricks-migration-accelerator-${{ github.ref_name }}.zip
            
      # - name: Create release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref_name }}
      #     release_name: ${{ github.ref_name }}
      #     draft: true
      #     prerelease: true
      #     body: "Release ${{ github.ref_name }}"
          
      # - name: Upload release asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: "powerbi-on-databricks-migration-accelerator-${{ github.ref_name }}.zip"
      #     asset_name: "powerbi-migration-accelerator-${{ github.ref_name }}.zip"
      #     asset_content_type: application/zip
